### ISSUE TITLE
рефакторинг

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/js-users-array#1]
https://github.com/DenisPitsul/js-users-array/blob/af9281eb12d7961112dc5d13c62e5c06df66dc3e/assets/js/index.js#L58-L63
- так буде більш в стилі жс:
```javascript
const subscribedUsersCount = users
    .filter(u => u.isSubscribed)
    .reduce((acc, user) => ++acc, 0);
``` 
а ще легше
```javascript
const subscriberUsers = users.filter(u => u.isSubscribed)
const subscribedUsersPercentage = ((subscriberUsers.length / users.length) * 100).toFixed();
```

**Comment by DenisPitsul** [comment]
Refactored in commit:
https://github.com/DenisPitsul/js-users-array/commit/8faf1c239f4fa7212a9d8c36053fcafd199b5ffc
